name: "Epic "
description: Register a new epic for the project
title: "{{ brief epic summary }}"
labels: 
  - "epic"
type: Epic
assignees:
  - commitybyguardia
projects:
  - "guardiatechnology/3"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing with an epic! Please fill out the fields below clearly and objectively.

  - type: textarea
    id: epic-why-is-this-important
    attributes:
      label: Why is this important?
      description: "What is the impact of this epic?"
      placeholder: ex. This epic is important because it will help us to track the progress of the stories within it.
      value: |
        Why is this important?
    validations:
      required: true

  - type: textarea
    id: epic-what-is-this-about
    attributes:
      label: What is this about?
      description: "Describe the epic in detail"
      placeholder: ex. This epic is about the user stories within it.
      value: |
        What is this about?

